### PR TITLE
support the option for fiat onboarding/offboarding #642

### LINKED ISSUE #642: support the option for fiat onboarding/offboarding
as a user, i would like to have the option to buy crypto with fiat or swap my crypto back to fiat.
note, we are NOT associated with the solution, just listing few selected options to make it available for our users.

side menu item:

page layout:
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=548%3A7980

moonpay implementation URL:
buy: https://buy.moonpay.com?apiKey=pk_live_qiJRayRj9iKRUWCfaWX5Vo6Sn0rnNsj&defaultCurrencyCode=ETH
sell: https://sell.moonpay.com?apiKey=pk_live_qiJRayRj9iKRUWCfaWX5Vo6Sn0rnNsj&defaultCurrencyCode=ETH

test key:
pk_test_UQrsGSrVtsrfN5O5IZUPJCDW5kXrrapO

### PR DESCRIPTION
**Pull request by sirius651**
Fix #642 

스크린샷 2021-01-28 오후 2 35 19

### CODE REVIEW

**Comment by Velua** [comment]
@pingustar can we get a preview link for this one?

**Comment by pingustar** [comment]
@Velua this branch and PR seems to be created before the preview workflow was added. I assume merging staging or master into this branch to update it should create a preview link.

**Comment by Velua** [comment]
@ashachaf this looks good to me, do you want to review it?

**Review by Velua — APPROVED** [review]

**Comment by ashachaf** [comment]
preview url doesnt work for me

**Comment by ashachaf** [comment]
@Velua can you bring the preview url back to life?

**Comment by Velua** [comment]
> @Velua can you bring the preview url back to life?

https://bancor-v2-beta--pr1120-feature-fiat-onboard-vvxwe07h.web.app/

**Comment by ashachaf** [comment]
please update the text:
title: Crypto<>Fiat Gateway Providers

subtitle: Below is a list of popular crypto<>fiat gateways that can be used to buy or sell crypto with a credit card, bank transfer & more.

Disclaimer: Crypto<>fiat gateway services on Bancor are provided by third-parties. Bancor is not associated with, responsible or liable for the performance of these third-party services. Any claims and questions should be addressed with the selected provider directly.

**Comment by ashachaf** [comment]
i do not see the text updates on the preview link
@pingustar can you help?

**Comment by ashachaf** [comment]
> > i do not see the text updates on the preview link
> > @pingustar can you help?
> 
> @ashachaf looks like there are two PR floating around. PR #1120 and #855
> 
> Text was updated on 855 https://bancor-v2-beta--pr855-fiat-onboarding-642-wsnkv8nb.web.app/eth/fiat
> 
> but it seems that the sidebar menu is not working there.

fiat page looks fine.
how can we push this?

**Comment by pingustar** [comment]
closing this in favor of #1120

**Pull request closed without merging**
