### PR TITLE
Feature/rx optimistic

### PR DESCRIPTION
**Pull request by Velua**

### CODE REVIEW

**Comment by Velua** [comment]
@ashachaf Try this, should be a bit quicker now.

**Comment by Velua** [comment]
Reviewing rewards not showing up

**Comment by Velua** [comment]
@ashachaf I've since updated it so that the browser will now cache the latest contract addresses, will attempt to fetch the data assuming the cached data is correct, if not, will try again when the contracts are fetched.

**Comment by ashachaf** [comment]
@Velua 
testing this out and i see empty data on the protection table
image

**Comment by ashachaf** [comment]
@Velua what is the status of this?
require qa?

**Comment by Velua** [comment]
Yeah further testing required and now we'll soon be doing the 15 second interval API request there's a bit more. 

We're caching the users position ID's so there's been extra logic required to ensure bad side effects and things happen.

**Comment by yudilevi** [comment]
@Velua keep in mind the data is going to come from the API soon.
Not to say we shouldn't cache it but remember that cache always has a bunch of issues associated with it (stale data etc.).

**Comment by ashachaf** [comment]
@Velua 
not sure if you've updated something or not, but protection data is still empty.

image

**Comment by Velua** [comment]
@pingustar I've made some breaking changes as there are now more optional props from ViewPositions are there was before.

**Comment by Velua** [comment]
@ashachaf you can test the slippage calculations on this branch.

**Comment by ashachaf** [comment]
some qa on ropsten:
1. data -> add liquidity single side -> enter bnt amount 1 -> click "stake and protect" -> nothing happens
image
2. data -> add liquidity dual side -> after clicking the stake confirmation, user is redirected into a blank page (expected, open the portfolio/pool tokens tab
current: 
image
expected:
image

**Comment by Velua** [comment]
Ropsten 

- [ ] Failed to add single single liquidity
- [ ] At the end of the process it brought me into a empty screen on dual sided, then ended up navigating to a 404. 
- [ ] 404 issue where the user cannot navigate away

**Comment by Velua** [comment]
- [ ] Orders don't seem to be showing up in the table - @Velua

**Comment by ashachaf** [comment]
- [ ] add a "powered by" text at the bottom of the widget (below the call to action button) - "Limit orders are powered by KeeperDAO" (see mockup)
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2606%3A5098
- [ ] add supporting text to the confirmation popup (see mockup)
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2606%3A5098

**Comment by Velua** [comment]
- [ ] Log out issues 
- [ ]

**Pull request merged**
