### PR TITLE
add whitelist loading state

### PR DESCRIPTION
**Pull request by pingustar**

### CODE REVIEW

**Comment by ashachaf** [comment]
when my wallet is connected, the option to add liquidity is disabled for few seconds. 
if we can force a check once a user clicks the "add liquidity", it might be better.

**Comment by pingustar** [comment]
> when my wallet is connected, the option to add liquidity is disabled for few seconds.
> if we can force a check once a user clicks the "add liquidity", it might be better.

 I have to disable or hide the button until the witelist data is loaded so I can determine if where to navigate to:

Whitelist = true -> single side
.Whitelist = false -> dual side

**Comment by ashachaf** [comment]
ok lets proceed with this option. disabled until you get the data

**Comment by pingustar** [comment]
> ok lets proceed with this option. disabled until you get the data

I optimized it a bit, I added a loading animation to make more clear why the button is disabled.

**Comment by ashachaf** [comment]
looks fine. can push.

**Comment by ashachaf** [comment]
is it super slow on purpose?
ok to push.

**Pull request merged**
