### PR TITLE
Transaction confirmation popup - show etherscan link right away #585

### LINKED ISSUE #585: Transaction confirmation popup - show etherscan link right away
Currently, when the user submits a transaction, we show a popup that's waiting for the tx confirmation, and only after the tx is confirmed, we show a "transaction confirmed" message with the link to etherscan.
A better approach is to show a "transaction submitted" popup and immediately show the etherscan URL and allow the user to track it there.

### PR DESCRIPTION
**Pull request by sirius651**
Fixes #585 

Setting resolveImeediately as true at resolveTxOnConfirmation function In the last transaction.

- addProtection
- removeProtection
- protectLiquidity
- addLiquidity
- removeLiquidity

### CODE REVIEW

**Comment by sirius651** [comment]
I found that after submitting a transaction with resolveImmediately, balance is not immediately synced in the list.
It is not clear whether there is a possibility of bugs when the UI action is executed during the confirmation process. 
any thoughts?
@Velua @pingustar

**Comment by Velua** [comment]
@sirius651 Do you wanna perform some test trades and adding liquidity on ropsten to test this out?

**Comment by sirius651** [comment]
> @sirius651 Do you wanna perform some test trades and adding liquidity on ropsten to test this out?

@Velua yes, I tested this on my side. but want to double check on your side. There could be an edge cases like problems while balance is out of sync on ui.

**Comment by Velua** [comment]
@pingustar can you take a look

**Review by pingustar — CHANGES_REQUESTED** [review]
@sirius651 

I have tested `add protection` for single and double which works great.

Please check, It didnt work for:
- Withdraw from protection


---



> I found that after submitting a transaction with resolveImmediately, balance is not immediately synced in the list....

not sure I follow, can you ping me about this.

**Comment by sirius651** [comment]
@pingustar 
Fixed 'withdraw' thing. 

> > I found that after submitting a transaction with resolveImmediately, balance is not immediately synced in the list....
> 
> not sure I follow, can you ping me about this.

스크린샷 2020-12-02 오후 5 46 46

For example, I put some amount and send transaction with it, then get tx confirmation message on popup. At that time, the balance is not updated. Because the confirmation hasn't been completed. so, as a user perspective, they should refresh it after checking the confirmation.

Prior to that, it seems to have waited for confirmation to be completed and called the below code. so, they can see updated balance right away.

```
const txHash = await this.resolveTxOnConfirmation({
      tx: contract.methods.removeLiquidity(dbId, ppmPercent),
      resolveImmediately: true
    });

    (async () => {
      await wait(600);
      this.fetchLockedBalances();
      this.fetchProtectionPositions({});
      await wait(2000);
      this.fetchLockedBalances();
      this.fetchProtectionPositions({});
    })();
```

so, I mean, if there's an action associated with the not updated balance, it might be affected.

**Comment by pingustar** [comment]
@sirius651 thanks for clarifying.

Good point, please raise this concern in the issue and tag @ashachaf or @yudilevi for further information on how to handle such case.

**Comment by Velua** [comment]
@sirius651 now that Yudi has [clarified](https://github.com/bancorprotocol/webapp/issues/585#issuecomment-737816863) does that get you out of trouble?

**Comment by sirius651** [comment]
> now that Yudi has [clarified](https://github.com/bancorprotocol/webapp/issues/585#issuecomment-737816863) does that get you out of trouble?

yes I think so. according to him, it can be merged. @Velua

**Review by pingustar — APPROVED** [review]

**Pull request merged**
