### PR TITLE
Update helpers.ts for Lattice1 Hardware Wallet Support

### PR DESCRIPTION
**Pull request by MidnightOnMars**
**Background**
The Lattice1 is GridPlus' next generation hardware wallet. It is an always-online device with physically separated compute environments which provide unmatched security. For more information, see https://gridplus.io/lattice

**About this PR**
This PR adds the Lattice1 as a wallet option for bnc-notify. The Lattice1 is supported in v1.14.0 which currently used by Bancor Swap.

Note that a (nearly) identical integration was added to Curve. [That pull request](https://github.com/curvefi/curve-vue/pull/6) has several photos documenting what it is like to connect to and use an app with the Lattice1 and bnc-notify.

Thanks and please let us know if you have any questions!

### CODE REVIEW

**Comment by Velua** [comment]
@H34D can you ensure this is using the right RPC configured and nurse it through?

**Comment by MidnightOnMars** [comment]
@Velua Thanks for taking a look at this - I went ahead and updated the RPC URL after reading your comment and double checking. Please let us know if you need any other info - thanks!

**Comment by H34D** [comment]
> @H34D can you ensure this is using the right RPC configured and nurse it through?

i will take a look today

**Comment by H34D** [comment]
merged, thanks for contributing!

**Pull request merged**
