### PR TITLE
Show tx confirm msg once tx is mined

### LINKED ISSUE #747: Vote start time text sizing issue
Vote start time header and value collide on mobile.

image

### PR DESCRIPTION
**Pull request by sirius651**
Fixes #747 #751

### CODE REVIEW

**Comment by sirius651** [comment]
스크린샷 2020-12-22 오후 2 05 41

#747

**Review by pingustar — CHANGES_REQUESTED** [review]
image

when rejecting the the tx, the modal is empty and the user has to refresh the page.

Lets try to use the same style and flow as we have it for swap. With button disabled when tx busy and saying try again, or close when success.

Also, lets clear the modal data when tx successful. So when I open the modal again I get empty input fields.

**Comment by sirius651** [comment]
> image
> 
> when rejecting the the tx, the modal is empty and the user has to refresh the page.
> 
> Lets try to use the same style and flow as we have it for swap. With button disabled when tx busy and saying try again, or close when success.
> 
> Also, lets clear the modal data when tx successful. So when I open the modal again I dont see the data that I just submitted.

thanks for good catch. fixed it you pointed out. @pingustar

**Review by pingustar — CHANGES_REQUESTED** [review]
Looking better.

When I reject the transaction the modal closes. It should stay open and show the error returned from metamask + the `Try Again` Button which brings you back to the input fields. That way the user can double check the data provided and can try again.

Take a look at the swap action and replicate that.

**Comment by sirius651** [comment]
> Looking better.
> 
> When I reject the transaction the modal closes. It should stay open and show the error returned from metamask + the `Try Again` Button which brings you back to the input fields. That way the user can double check the data provided and can try again.
> 
> Take a look at the swap action and replicate that.

스크린샷 2020-12-28 오후 11 49 15

Fixed. do you mean like this?

**Review by pingustar — CHANGES_REQUESTED** [review]
Almost, small adjustments as we discussed in zoom.

**Comment by sirius651** [comment]
> Almost, small adjustments as we discussed in zoom.

Fixed including remaining time text. hope to last answer for this task 😃

**Review by pingustar — APPROVED** [review]
Great job.

**Pull request merged**
