### PR TITLE
Sorting bugs

### PR DESCRIPTION
**Pull request by Ran73Cohen**
A ref for #1173
It seems that #1130 isn't happening anymore, however we did find a bug in the sorting that this PR fixes.
For those interested:
Go to data table
Sort APR a couple of times
The sort has 4 states instead of two

### CODE REVIEW

**Comment by Ran73Cohen** [comment]
@imperialyoyo Ty for this PR ❤️
I have simplified the sorting code a bit and reverted the changes made to the column width
Is there a reason we would like to extend the size of the APR column?
The protected table is getting a refactor so column changes will be scrapped anyway.

**Comment by imperialyoyo** [comment]
@Ran73Cohen when I test this on small devices, the arrow popped down to separate line if the column width was not extended by few pixels.  Also seen when you sort APR and all the values are 0.00 ( which is more of a Brave browser issue )

**Comment by imperialyoyo** [comment]
> It seems that #1130 isn't happening anymore, however we did find a bug in the sorting that this PR fixes.

I see the sort "reset" happening due to the way the NaN are handled, see attached vid.  The NaN changes should fix this

**Comment by Ran73Cohen** [comment]
> 
> 
> 
> 
> @Ran73Cohen when I test this on small devices, the arrow popped down to separate line if the column width was not extended by few pixels. Also seen when you sort APR and all the values are 0.00 ( which is more of a Brave browser issue )

Agreed and fixed.

**Comment by ashachaf** [comment]
https://streamable.com/f5c2zb

**Review by ashachaf — APPROVED** [review]

**Pull request merged**
