### PR TITLE
Investigate big-ass bundle size #465

### PR DESCRIPTION
**Pull request by sirius651**
**[Checkpoint]**

- webpack-bundle-analyzer
- code splitting, tree-shaking
- bundle optimization
-- decrease chunk sizes : CSS,JS Part optimization
-- reduce big library sizes : lodash, moments..
-- compress image assets
- Google Lighthouse
- browser network inspection tool

### CODE REVIEW

**Comment by sirius651** [comment]
- webpack-bundle-analyzer


스크린샷 2020-11-10 오후 4 11 47

**Comment by Velua** [comment]
@sirius651 any idea if we can tree shake with fort awesome?

**Comment by Velua** [comment]
Looks like the biggest quick wins would be 
- Fort awesome
    - Tree shaking or manually shipping icons, dependent on how much we're using it. 
- Chart.js - @pingustar we're not using charts atm are we? Can we remove this for now?
- Moment.js 
    - Bundle size is **288.4kb** while ```day.js``` is only **6.3kb**
- Using lodash individual libaries
    - There is an npm package for every ```lodash``` function which we could use instead of the whole library, I haven't done this before though as I failed to work out how to get the Typescript definitions to come along with it, seems like they don't ship in the packages and would be a real shame if we lost the type definitions. @sirius651 any ideas? Same deal with my ```eth-multicall``` library, really only use ```lodash``` a few times, shouldn't be shipping the whole damn thing. 
- Looks like the ```ipfs-http-client``` has a bit of weight to it as well, any ideas @H34D ?

**Comment by sirius651** [comment]
- moment.js
Once ignoring locale in moment.js in webpack, the file size has been reduced from 257 kb to 59 kb.

- tree shaking for font-awesome

I found all the icons that use `font-awesome-icon` and imported them individually. But, when doing like this
```
import { faArrowCircleRight, …} from "@fortawesome/free-solid-svg-icons";
```
the file size of `fontawesome` just reduced from ‘1.18MB’ to ‘1.04MB’.

So, I had to deep import each icon for tree-shaking.
```
import { faTwitter } from "@fortawesome/free-brands-svg-icons/faTwitter";
```
And, I created the `icons.ts` file separately and arranged it alphabetically. Keep in mind when you want to use new icon, you should define it at `icons.ts` ahead.

As a result, the font-awesome file size was reduced to **71.8 KB**, and the total file size was reduced from 9.64MB to 8.58MB.

스크린샷 2020-11-12 오후 4 03 54


The next thing I should look at would be lodash, bootstrap, PurgeCSS...

**Comment by Velua** [comment]
- [ ] Uninstall Chart.js
- [ ] Create a brand new issue on changing from ```moment.js``` to ```day.js```, not a big priority, just something to add to the back log.
- [ ] Investigate wtf ```torus``` is.

**Comment by sirius651** [comment]
Regarding [torus](https://github.com/torusresearch/torus-embed), it is derived from the [bnc-onboard](https://github.com/blocknative/onboard) library. And this includes squarelink and other modules, which takes up many sizes besides torus. 
Considering this, we should figure out `bnc-onboard` is a necessary module.

**Comment by sirius651** [comment]
Tried tree shaking with bootstrap-vue and tried to remove unused css by using purgeCSS, but I haven't seen much outcome. 
But, to tried tree shaking with lodash, I used the [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash).
the total file size was reduced to **8.44MB**.

**Comment by Velua** [comment]
Let's lock in our current work done so this work isn't too far behind today's version of staging. 

@sirius651 Do what you gotta do to make this ready, clear up any conflicts that may arise by merging to ```staging``` and mark then mark as *Ready for review* and I'll review it before merging.

**Comment by sirius651** [comment]
@Velua  Cleaned up, ready for merging. please review for this.

**Comment by H34D** [comment]
LGTM 👍🏻

**Pull request merged**
