### PR TITLE
Indication for rewards multiplier in protected table

### PR DESCRIPTION
**Pull request by Ran73Cohen**
#1055

### CODE REVIEW

**Comment by Ran73Cohen** [comment]
@ashachaf LMK If we want it to look a little different since there was no mockups.

**Comment by ashachaf** [comment]
functionality looks fine.
dont like the design.
will update that part.

**Comment by ashachaf** [comment]
it seems that you indicate multiplier for pools that do not have rewards.
can you identify pool positions that have rewards and identify their multiplier only?

**Comment by Ran73Cohen** [comment]
> 
> 
> it seems that you indicate multiplier for pools that do not have rewards.
> can you identify pool positions that have rewards and identify their multiplier only?

Will check the data again.

**Comment by ashachaf** [comment]
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2924%3A911

update the following:
column title "fees & rewards" update tool tip: 
Fees are generated when traders swap in pools where you provide liquidity. Rewards are bonuses paid in BNT to liquidity providers.

mouse over rewards amount and multiplier, display this tool tip: 
  Starting at 1, your multiplier increase .25 each week until reaching 2.  At which point, you are getting twice the rewards you were on week 1. The number to the left already takes this into account. 

mouse over rewards ROI, display this tool tip:
Your ROI from fees (top) and rewards (bottom). Combined they represent your full ROI.

mouse over vesting counter, display this tool tip: 
Current protection is {amount}

**Comment by Ran73Cohen** [comment]
Continue in #1171

**Pull request closed without merging**
