### PR TITLE
Fix css issue on voting page

### PR DESCRIPTION
**Pull request by sirius651**
스크린샷 2020-12-10 오후 5 11 38
스크린샷 2020-12-10 오후 5 11 10

### CODE REVIEW

**Comment by sirius651** [comment]
Tested both web and mobile. can you point out if any missing things? @pingustar @H34D

**Review by pingustar — APPROVED** [review]
LGTM

**Comment by pingustar** [comment]
Great job @sirius651 looking good.

Last thing I noticed is that it is missing the separator line between each proposal.

**Comment by H34D** [comment]
@sirius651 maybe we can hide this border somehow when it collapses? it would save some space

Screenshot 2020-12-10 at 12 10 49

**Comment by sirius651** [comment]
Good point. I updated PR for tackling that issue

**Pull request merged**
