### PR TITLE
replace hardcoded gas values with estimateGas

### LINKED ISSUE #726: gas estimation is too high on the transactions
as a user, i would like to receive a cost estimation that is close to the actual cost.
currently, it seems we average 35%-45% over estimate the gas required for every transaction and the result is "scaring" people off by perceived higher prices (eventually, the user will pay 35%-45% less on the transaction).

#### example:
go to swap
attempt to execute eth->link swap
estimation: 462,636 gas units
actually used: 294,403 (63.64%)
https://etherscan.io/tx/0x577edaad990a2db84b02f52d3267ab413b2a30cc2e3d7d1d20b82805f51f7ace

#### approve transaction:
go to swap -> convert link->eth and the first transaction is approve.
estimation: 70,000 gas units
actually used: 14,628 (20.9%) **(this is an extreme buffer!)**
https://etherscan.io/tx/0x5dce29176ecdb2a7410e659bde806568cdca0bed43cedeb45d6c3e37c03bff75

### we would like to aim for 10%-15% gas units buffer on the transactions we build.

### PR DESCRIPTION
**Pull request by H34D**
use estimateGas instead of hardcoded gas values

fixes #726

### CODE REVIEW

**Review by Velua — APPROVED** [review]

**Review by Velua — CHANGES_REQUESTED** [review]
Hold up, I'm running convert and still getting the ```execution reverted``` error when doing the estimation. This doesn't happen for you?

**Comment by H34D** [comment]
> Hold up, I'm running convert and still getting the `execution reverted` error when doing the estimation. This doesn't happen for you?

its not happening for me

**Comment by Velua** [comment]
@pingustar Can you run this branch in your dev environment and see if you get an error thrown when you hit the ```convert``` method when attempting a transaction? You don't need to approve in MetaMask. 

For some reason this ```estimateGas``` function throws for me but not for @H34D

**Comment by pingustar** [comment]
> @pingustar Can you run this branch in your dev environment and see if you get an error thrown when you hit the `convert` method when attempting a transaction? You don't need to approve in MetaMask.
> 
> For some reason this `estimateGas` function throws for me but not for @H34D

Do we have this issue on ropsten or mainnet?

on ropsten it works fine, approval -> convert -> success

on mainnet it is asking for approval which also has no error. (didnt confirm it to get to the conversion tx)

**Comment by Velua** [comment]
God damn... Alright let me mess around with my metamask or something.

**Comment by H34D** [comment]
given up for #866

**Pull request closed without merging**
