### PR TITLE
move getGeometricMean and fetchRelayBalances requests to alchemy

### PR DESCRIPTION
**Pull request by H34D**

### CODE REVIEW

**Comment by Velua** [comment]
What's the strategy here? We want some requests to through Alchemy and others through elsewhere?

**Comment by H34D** [comment]
> What's the strategy here? We want some requests to through Alchemy and others through elsewhere?

the strategy is to do as much as possible through alchemy, those were missing and some others as well

**Comment by Velua** [comment]
Lets go over this one in a call.

**Comment by H34D** [comment]
implemented with hotfix #515

**Pull request closed without merging**
