### PR TITLE
Add jest config for mocking api/helpers

### PR DESCRIPTION
**Pull request by sirius651**
- Add jest config for mocking current `api/helpers.ts`, which is linked to `tests/unit/__mocks__/helpersMock.ts`
- Recommend you move `prettifyNumber` in `helpers.ts` to in `pureHelpers.ts`. The functions that do not import other libraries, such as vxm, need to be isolated in `pureHelpers.ts`.

### CODE REVIEW

**Comment by pingustar** [comment]
Ask discussed in the meeting this morning, I have created a new `prettifyNumber` function in `pureHelpers.ts` this new function is a work in progress and doesnt rely on `BigNumber` or `numeral` but I was getting a bunch of rounding errors.

**Comment by sirius651** [comment]
> Ask discussed in the meeting this morning, I have created a new `prettifyNumber` function in `pureHelpers.ts` this new function is a work in progress and doesnt rely on `BigNumber` or `numeral` but I was getting a bunch of rounding errors.

Is it because of testing that you don't use that libraries? As I tested again, it seems no problems with both libraries. 
anyway, this commits are for ignoring imports `helpers.ts` on components

**Comment by pingustar** [comment]
@sirius651 `prettifyNumbers` currently requires `BigNumber` and `numeral` therefore it is not a `pureHelper` or not?

Can we use `BigNumber` and `numeral` in `pureHelper`? I thought you said we cannot test any helpers/components that rely on third party libraries?

**Comment by pingustar** [comment]
I made some changes, seems to work now. Thanks

**Comment by sirius651** [comment]
> yes, because you mentioned on friday that testing wont work with these dependencies.
> 
> @sirius651 `prettifyNumbers` currently requires `BigNumber` and `numeral` therefore it is not a `pureHelper` or not?
> 
> Can we use `BigNumber` and `numeral` in `pureHelper`? I thought you said we cannot test any helpers/components that rely on third party libraries?

Not all third-party libraries do not work. I'm not sure which libraries work, but most vxm libraries seem to have problems with importing router.

**Comment by pingustar** [comment]
it seems to work now, all good.

**Pull request merged**
