### PR TITLE
Feature/update protected table proposal

### PR DESCRIPTION
**Pull request by pingustar**
Referencing https://github.com/bancorprotocol/webapp/pull/1064

### CODE REVIEW

**Review by Ran73Cohen — APPROVED** [review]
LGTM

**Comment by JPanneel** [comment]
Hey, thanks for the code review! Did you perhaps had the time assess if this is a change you would like to make to the UI? Would like to know how to proceed if it is and why not if it is not.

**Comment by Velua** [comment]
We'll be writing some unit tests for the current end result and then will be in a better position to ensure there's no breaking changes here.

**Comment by Ran73Cohen** [comment]
@JPanneel
Ty for this feature
We have been working on changes to protection table and your feature was included in this [PR](#1176) and is now in production
There is a major refactor to the protection table design which is happening [here](#1166) which will also take these changes into consideration

**Comment by JPanneel** [comment]
Nice, thanks @Ran73Cohen for the update. I am happy to have contributed!

**Pull request merged**
