### PR TITLE
Fix testing method #464

### LINKED ISSUE #464: Fix testing method

### PR DESCRIPTION
**Pull request by sirius651**
# Main Goal
- [x] Update testing so that it supports ```.ts``` files instead of the current ```.js``` ones
- [ ] Confirm direct imports of functions into these test files works okay. 
- [ ] Come up with a component testing solution.
- [ ] Bonus: Any Vuex related testing libraries? What's the most professional way for assessing it. 

## Todo
- [x] Jest configuration
- [x] Write test file with direct imports
- [x] Try to test component with Jest
- [x] Try to test vuex with localVue

## Might be solution
- Upgrade latest version of cli
- [jest-fetch-mock](https://github.com/jefflau/jest-fetch-mock)
- [vuex-module-decorator](https://github.com/championswimmer/vuex-module-decorators)
- [vue-class](https://github.com/ktsn/vuex-class)

Resolve #464

### CODE REVIEW

**Comment by Velua** [comment]
Here is that link - https://jestjs.io/docs/en/ecmascript-modules

**Comment by sirius651** [comment]
To resolve testing issue, what I did so far
- Switch to new version of cli(babel, jest, eslint ...) and change presets in config
- Add transformIgnore option in jest.config (it seems tricky)
- To support fetch in jest, use `jest-fetch-mock`
- Because component is connection with vuex store, we can use `localVue`, which makes isolated area not including dependencies.
- So, we can make separate testing as UI testing, Vuex testing, etc.

**Comment by Velua** [comment]
@H34D Dropped in these bad boys for us 
- https://vue-test-utils.vuejs.org/guides/using-with-vuex.html  
- https://github.com/ktsn/vuex-class

**Comment by Velua** [comment]
Also awesome work @sirius651 can definitely imagine this one being a pain in the ass.

**Comment by elegant651** [comment]
The current situation I have approached for VueX and component testing is to remove the existing coupled vuex-class-component and make sure it can be replaced. 
First off, I used with pure vuex modules such as `Module, GetterTree, MutationTree, ActionTree`. but, it made a boilerplate code a bit.
So, I reached out that as a good combination, vuex uses [vuex-module-decorator](https://github.com/championswimmer/vuex-module-decorators), and [vue-class](https://github.com/ktsn/vuex-class) in components.
With this, we can write a testable code and mocking store is also possible. Also, to implement vuex store is very similar to the current code method.

**Comment by Velua** [comment]
Let's re-prioritise and see if we can get import vanilla Typescript functions into the test files and perform tests against them. 

This way we have something to work with for now until we further determine the trade offs between the current ```vxm``` system and supporting the Vuex mocking with these bonus libraries. 

Reach out to me on Telegram and we'll have a call to further discuss this if you like.

**Comment by Velua** [comment]
@sirius651

**Comment by sirius651** [comment]
Yes, I tried it before, and even I tried to mock some modules for this, not working well.
Let me explain what’s going on in detail.

Of course, we can test files that do not import other libraries. But, for `/api/helpers.ts`, which is import `vxm` and others, it encountered errors like below.

스크린샷 2020-11-10 오전 11 35 47

Following to the event log, 

Call Test file => `src/store/index.ts` (from vxm) => import all store modules at once => some modules (`src/store/modules/swap/index.ts`) contains `router` file => Because `router` file does not call the component using lazy loading, it import all components at once. => each component call other utility function

So, this situation is the same as component testing I got. That’s why I suggested separating the combined elements of vuex store basically. Even though I tried with jest mocking stuff, it didn’t succeed unfortunately.

Do you think my approach is the right way? or we can discuss this more detail online.
@Velua

**Comment by Velua** [comment]
Are we able to create a working demo of an example of a pure component (one not reliant on anything than props) ? 
Just want to get a better idea of the returns we would get should we revamp ```vxm``` to support this. How meaningful will these tests be to us? 

Lets get ```TS``` test files and direct imports, I have a new math functions I could use tests for ASAP. My current understanding is that we are able to do this in this current branch but cannot import functions from the ```helpers.ts``` file or any other file which is importing ```vxm``` ? I'll work from a brand new file, ```pureMaths.ts``` or something like that. 

So if it's easiest to fork from this branch and ship this as a mini feature or just fork again from ```staging``` whatever is easiest.

**Comment by Velua** [comment]
@sirius651 @pingustar Some ideas on the [why](https://vuejs.org/v2/cookbook/unit-testing-vue-components.html#Why-test)

Component testing will be handy for confirming errors are thrown when balances are insufficient, we can also mock responses from the Vuex methods so things like conversion estimates and things are returned, formatting is as we're expecting. This should scale nicely.

**Comment by Velua** [comment]
// Component Layer
// Is the ability to inject Vuex Store
// Current system
// Directed import of a random VXM object, which could be anything
// This new system
// Utilises vuex-class which allows us to just specify namespace
// and then Vuex magically injected into it and works.

// Why can't the existing modules in the existing namespace, be adopted here
// why is it warranted for the modules to adopt another Decorator system, which

**Comment by sirius651** [comment]
I tried testing with the existing vuex store and it seems to work well. The error in the test earlier was only the namespace name of mocking module was wrong. I committed it to the current branch.
So, no need to refactor current all vuex store, just only we can focus on vue component things with `[vuex-class](https://github.com/ktsn/vuex-class)`.

**Comment by Velua** [comment]
Awesome stuff @sirius651 

Is this a way that works with testing? 
```

import { namespace } from "vuex-class";

const bancor = namespace("bancor");

@Component
export default class ActionModalStatus extends Vue {
  @bancor.Getter currentNetwork!: string;

}

```

**Comment by sirius651** [comment]
> Awesome stuff @sirius651
> 
> Is this a way that works with testing?
> 
> ```
> 
> import { namespace } from "vuex-class";
> 
> const bancor = namespace("bancor");
> 
> @Component
> export default class ActionModalStatus extends Vue {
>   @bancor.Getter currentNetwork!: string;
> 
> }
> ```

Yes, that way reduce boilerplate codes. works smoothly

**Pull request merged**
